/*
 * This file is generated by jOOQ.
 */
package net.cactusthorn.micro.db.jooq.tables.records;


import java.time.LocalDateTime;

import net.cactusthorn.micro.db.jooq.embeddables.records.AuditRecord;
import net.cactusthorn.micro.db.jooq.tables.Customer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record5<Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>customer.address_id</code>.
     */
    public void setAddressId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.address_id</code>.
     */
    public Integer getAddressId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>customer.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for the embeddable <code>audit</code>.
     */
    public void setAudit(AuditRecord value) {
        set(3, value.getCreatedOn());
        set(4, value.getModifiedOn());
    }

    /**
     * Getter for the embeddable <code>audit</code>.
     */
    public AuditRecord getAudit() {
        return new AuditRecord(
              (LocalDateTime) get(3)
            , (LocalDateTime) get(4)
        );
    }

    /**
     * Setter for <code>customer.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>customer.modified_on</code>.
     */
    public void setModifiedOn(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer.modified_on</code>.
     */
    public LocalDateTime getModifiedOn() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customer.CUSTOMER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Customer.CUSTOMER.ADDRESS_ID;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.EMAIL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Customer.CUSTOMER.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Customer.CUSTOMER.MODIFIED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAddressId();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAddressId();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedOn();
    }

    @Override
    public CustomerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(Integer value) {
        setAddressId(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomerRecord value4(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public CustomerRecord value5(LocalDateTime value) {
        setModifiedOn(value);
        return this;
    }

    @Override
    public CustomerRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer id, Integer addressId, String email, LocalDateTime createdOn, LocalDateTime modifiedOn) {
        super(Customer.CUSTOMER);

        setId(id);
        setAddressId(addressId);
        setEmail(email);
        setCreatedOn(createdOn);
        setModifiedOn(modifiedOn);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer id, Integer addressId, String email, AuditRecord audit) {
        super(Customer.CUSTOMER);

        setId(id);
        setAddressId(addressId);
        setEmail(email);
        setAudit(audit);
    }
}
