/*
 * This file is generated by jOOQ.
 */
package net.cactusthorn.micro.db.jooq;


import net.cactusthorn.micro.db.jooq.tables.Country;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_COUNTRY_ALPHA2 = Internal.createIndex(DSL.name("idx_country_alpha2"), Country.COUNTRY, new OrderField[] { Country.COUNTRY.ALPHA2 }, true);
    public static final Index IDX_COUNTRY_ALPHA3 = Internal.createIndex(DSL.name("idx_country_alpha3"), Country.COUNTRY, new OrderField[] { Country.COUNTRY.ALPHA3 }, true);
}
