/*
 * This file is generated by jOOQ.
 */
package net.cactusthorn.micro.db.jooq;


import net.cactusthorn.micro.db.jooq.tables.Address;
import net.cactusthorn.micro.db.jooq.tables.Country;
import net.cactusthorn.micro.db.jooq.tables.Customer;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;
}
